import { Toaster } from "@/components/ui/sonner";
import { Montserrat } from "./fonts/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "La casa del Junior",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${Montserrat.variable}`}> 
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
