import { AuthProvider } from "../context/AuthContext";
import { Toaster } from "../components/ui/sonner";
import { getProfile } from "../lib/supabase/rol";
import { Montserrat } from "./fonts/fonts";
import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "La casa del Junior",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className={`${Montserrat.variable}`}>
      <body>
        <Suspense fallback={null}>
          <AuthBootstrap>
            {children}
          </AuthBootstrap>
        </Suspense>
        <Toaster />
      </body>
    </html>
  )
}

const AuthBootstrap = async ({ children }: { children: React.ReactNode }) => {
  const profile = await getProfile()
  return (
    <AuthProvider initialData={profile}>
      {children}
    </AuthProvider>
  )
}