services:
  next-app:
    container_name: blog
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["pnpm", "dev"]
    env_file:
      - .env
    volumes:
      - ./front:/app
      - /app/node_modules
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres_db
    networks:
      - my_network

  postgres_db:
    container_name: db
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PG_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
