FROM node:23-alpine

WORKDIR /app

# Instala dependencias
COPY /front/package.json front/pnpm-lock.yaml ./
RUN corepack enable && \
    pnpm install

# Copia todo el código
COPY . .

CMD ["pnpm", "dev"]